sudo: required 
services:
  - docker

before_install:
  - docker build -t gyamanoudemy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gyamanoudemy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerex"
  env: "Dockerex-env"
  bucket_name: "elasticbeanstalk-us-east-2-577522661097"
  bucket_path: "dockerex"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

